#IT0425 - Introducción a la Inteligencia Artificial

### Otoño 2023

### IT0425_Lab_1-8

**Profesor Enrique Naredo García**

<font size = 2>
©️ Todos los derechos reservados. All rights reserved.

*Nota: El presente documento es una herramienta diseñada única y exclusivamente para los estudiantes de la asignatura arriba mencionada. Se recuerda no compartir esta información fuera de los integrantes registrados en este curso. La reproducción total o parcial de este documento requiere autorización por escrito del titular del copyright.*
</font>

#Algoritmo de búsqueda A*

La [heurística de búsqueda A*](https://es.wikipedia.org/wiki/Algoritmo_de_b%C3%BAsqueda_A*) (pronunciado "A asterisco", "A estrella" o "A star" en inglés) se clasifica dentro de los algoritmos de búsqueda en grafos de tipo heurístico o informado.

* Presentado por primera vez en 1968 por Peter E. Hart, Nils J. Nilsson y Bertram Raphael.

* El algoritmo A* encuentra soluciones, siempre y cuando se cumplan unas determinadas condiciones.

* El algoritmo selecciona el camino de menor costo entre un estado inicial y otro final.

El algoritmo A* utiliza una función de evaluación
$$f (n) = g (n) + h(n)$$

* donde $g(n)$, es el costo real del camino recorrido para llegar a un nodo (estado).
* y $h(n)$, es el valor heurístico del nodo (estado) a evaluar hasta el estado final (objetivo).

En este ejemplo, se muestra la implementación del algoritmo A* en Python.

In [ ]:
# librerías
from copy import deepcopy
import numpy as np
import time

In [ ]:
# estado inicial (lista)
inicial = [2, 8, 3, 1, 6, 4, 7, 0, 5]

In [ ]:
# convierte a matriz de 3x3
inic_3x3 = np.array(inicial).reshape(3,3)
print(inic_3x3)

[[2 8 3]
 [1 6 4]
 [7 0 5]]


In [ ]:
# muestra matriz sin corchetes
print(str(inic_3x3).replace('[', ' ').replace(']', ''))

  2 8 3
  1 6 4
  7 0 5


In [ ]:
# estado final
final = [1, 2, 3, 8, 0, 4, 7, 6, 5]

# convierte a matriz de 3x3
final_3x3 = np.array(final).reshape(3,3)

# muestra matriz sin corchetes
print(str(final_3x3).replace('[', ' ').replace(']', ''))


  1 2 3
  8 0 4
  7 6 5


In [ ]:
# se usa tablero porque se actualiza con cada movimiento
tablero = inicial

In [ ]:
# coordenadas
def coordenadas(tablero):
    pos = np.array(range(9))
    for p, q in enumerate(tablero):
      pos[q] = p
    return pos


In [ ]:
# solo de prueba
def coordenadas2(tablero):
    pos = np.array(range(9))
    print(pos)
    for p, q in enumerate(tablero):
      print(p,q)
      pos[q] = p
      print(pos)
    return pos

In [ ]:
# muestra como opera enumerate
coordenadas2(tablero)
# indices -> [0, 1, 2, 3, 4, 5, 6, 7, 8]
# tablero -> [2, 8, 3, 1, 6, 4, 7, 0, 5]
# 1er iteración: tablero[0]=>2
# pos[0]=2, tablero[2]=0
# 2da iteración: tablero[1]=>8
# pos[1]=8, tablero[8]=1

[0 1 2 3 4 5 6 7 8]
0 2
[0 1 0 3 4 5 6 7 8]
1 8
[0 1 0 3 4 5 6 7 1]
2 3
[0 1 0 2 4 5 6 7 1]
3 1
[0 3 0 2 4 5 6 7 1]
4 6
[0 3 0 2 4 5 4 7 1]
5 4
[0 3 0 2 5 5 4 7 1]
6 7
[0 3 0 2 5 5 4 6 1]
7 0
[7 3 0 2 5 5 4 6 1]
8 5
[7 3 0 2 5 8 4 6 1]


array([7, 3, 0, 2, 5, 8, 4, 6, 1])

In [ ]:
# verifica la mejor solución
def mejorSolucion(estado):
    mejor = np.array([], int).reshape(-1, 9)
    contador = len(estado) - 1
    while contador != -1:
        mejor = np.insert(mejor, 0, estado[contador]['tablero'], 0)
        contador = (estado[contador]['nodo_padre'])
    return mejor.reshape(-1, 3, 3)

In [ ]:
# heurística: cantidad de cuadros (números) mal colocados
def malColocados(tablero, final):
    costo_mc = np.sum(tablero != final) - 1
    return costo_mc if costo_mc > 0 else 0

In [ ]:
# utiliza la heurística de cuadros mal colocados
def Algo_UnaEstrellita(tablero, final):
  movimientos = np.array([
            ('N', [0, 1, 2], -3),
            ('S', [6, 7, 8],  3),
            ('O', [0, 3, 6], -1),
            ('E', [2, 5, 8],  1)],
            dtype = [('mueve',  str, 1),('posicion', list),('enfrente', int)]
          )
  # distancia
  dist_estado = [('tablero',  list),('nodo_padre', int),('gn', int),('hn',  int)]
  # costo a la meta
  costo_meta = coordenadas(final)
  # inicializa el nodo padre
  nodo_padre = -1
  # gn=costo_mov
  gn = 0
  # hn=valor_heuristico
  hn = malColocados(coordenadas(tablero), costo_meta)
  # estado actual
  estado = np.array([(tablero, nodo_padre, gn, hn)], dist_estado)
  # colas prioritarias con posicion como "key" y fn como "valor"
  prioridad_cola = [('posicion', int),('fn', int)]
  # prioridad
  prioridad = np.array([(0, hn)], prioridad_cola)
  # ciclo infinito (continuo)
  while True:
    # actualización de la prioridad
    prioridad = np.sort(prioridad, kind='mergesort', order=['fn', 'posicion'])
    # la más alta prioridad
    posicion, fn = prioridad[0]
    # ordena la prioridad de la cola, selecciona el 1er elemento por explorar
    prioridad = np.delete(prioridad, 0, 0)
    # actualiza heurística
    tablero, nodo_padre, gn, hn = estado[posicion]
    # y el tablero
    tablero = np.array(tablero)
    # hueco
    hueco = int(np.where(tablero == 0)[0])
    # siguiente valor de gn
    gn = gn + 1
    # contador
    c = 1
    # incia conteo de tiempo (reloj)
    tiempo_inicial = time.time()
    # ciclo de movimientos
    for s in movimientos:
      # contador
      c = c + 1
      # verifica que el hueco no este en la posición actual
      if hueco not in s['posicion']:
        # realiza una copia del estado actual del rompecabezas
        estados_sinExplorar = deepcopy(tablero)
        # entonces visita los estados sin explorar
        estados_sinExplorar[hueco], estados_sinExplorar[hueco + s['enfrente']] =\
                   estados_sinExplorar[hueco + s['enfrente']], estados_sinExplorar[hueco]
        # si no existe estados por explorar
        if ~(np.all(list(estado['tablero']) == estados_sinExplorar, 1)).any():
          # finaliza reloj
          tiempo_final = time.time()
          # compara el tiempo de ejecución
          if (( tiempo_final - tiempo_inicial ) > 2):
            # si es mayor a 2 seg, imprime:
            print(" El rompecabezas no se puede resolver.\n")
            # y sale del ciclo for
            break
          # verifica los cuadros mal colocados
          hn = malColocados(coordenadas(estados_sinExplorar), costo_meta)
          # genera y agrega un nuevo estado a la cola
          q = np.array([(estados_sinExplorar, posicion, gn, hn)], dist_estado)
          # actualiza el estado actual
          estado = np.append(estado, q, 0)
          # fn es la sumatoria de los costos para moverse al nodo
          fn = gn + hn
          # actualiza el nuevo estado
          q = np.array([(len(estado) - 1, fn)], prioridad_cola)
          # asigna nueva prioridad al estado
          prioridad = np.append(prioridad, q, 0)
          # compara el estado actual al final (objtivo)
          if np.array_equal(estados_sinExplorar, final):
            # imprime que si se puede resolver
            print(' El rompecabezas si se puede resolver. \n')
            # regresa el estado y su prioridad
            return estado, len(prioridad)
  # regresa el estado y su prioridad
  return estado, len(prioridad)


In [ ]:
# prueba algoritmo
estado, visitado = Algo_UnaEstrellita(inicial, final)

 El rompecabezas si se puede resolver. 



In [ ]:
# verifica la mejor secuencia de movimientos
mejorSecuencia = mejorSolucion(estado)

In [ ]:
# imprime la mejor secuencia
print(str(mejorSecuencia).replace('[', ' ').replace(']', ''))

   2 8 3
   1 6 4
   7 0 5

   2 8 3
   1 0 4
   7 6 5

   2 0 3
   1 8 4
   7 6 5

   0 2 3
   1 8 4
   7 6 5

   1 2 3
   0 8 4
   7 6 5

   1 2 3
   8 0 4
   7 6 5


In [ ]:
# muestra la cantidad total de movimientos
totalMovimientos = len(mejorSecuencia) - 1
print('\nMovimientos para resolver el rompecabezas:',totalMovimientos)


Movimientos para resolver el rompecabezas: 5


In [ ]:
# muestra el número de nodos visitados
numVisitados = len(estado) - visitado
print('Total de nodos visitados: ',numVisitados, "\n")

Total de nodos visitados:  6 

