#IT0425 - Introducción a la Inteligencia Artificial

### Otoño 2023

### IT0425_Lab_1-10

**Profesor Enrique Naredo García**

<font size = 2>
©️ Todos los derechos reservados. All rights reserved.

*Nota: El presente documento es una herramienta diseñada única y exclusivamente para los estudiantes de la asignatura arriba mencionada. Se recuerda no compartir esta información fuera de los integrantes registrados en este curso. La reproducción total o parcial de este documento requiere autorización por escrito del titular del copyright.*
</font>

#Juego del "gato #"


El tres en línea, también conocido en México como juego del gato, también conocido en otros lugares como ceros y cruces, tres en raya, cerito cruz, michi, triqui, cuadritos, juego del gato, gato, tatetí, totito, triqui traka, equis cero, o la vieja.

* Es un juego de lápiz y papel (en sus origenes) entre dos jugadores: O y X, que marcan los espacios de un tablero de $3×3$ alternadamente.

In [1]:
# lirerías
import numpy as np
import random
from time import sleep

In [2]:
# creación de tablero vacio
def crea_tablero():
	return( np.array(
          [[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]
          )
        )

In [3]:
# verifica celdas vacias en el tablero
def celdas_vacias(tablero):
	lista = []
  # ciclo
	for i in range(len(tablero)):
		for j in range(len(tablero)):
      # si esta vacia agregala a la lista
			if tablero[i][j] == 0:
				lista.append((i, j))
  # regeresa la lista
	return lista

In [4]:
# seleciona aleatoriamente una celda
def movimiento_aleatorio(tablero, jugador):
	seleccion = celdas_vacias(tablero)
	nueva_posicion = random.choice(seleccion)
	tablero[nueva_posicion] = jugador
	return tablero

In [5]:
# verifica si ya ganó
# si tiene 3 en línea horizontalmente
def gana_horizontal(tablero, jugador):
  # recorre horizontalmente
  for x in range(len(tablero)):
    # asume que ya ganó
    gana = True
    # recorre verticalmente
    for y in range(len(tablero)):
      # si no hay 3 en línea
      if tablero[x, y] != jugador:
        # pues realmente no ha ganado
        gana = False
        # continua con el siguiente
        continue
    # si realmente ganó
    if gana == True:
      return gana
  # regresa gana
  return gana

In [6]:
# verifica si ya ganó
# si tiene 3 en línea verticalmente
def gana_vertical(tablero, jugador):
  # recorre horizontalmente
  for x in range(len(tablero)):
    # asume que ya ganó
    gana = True
    # recorre verticalmente
    for y in range(len(tablero)):
      # si no hay 3 en línea
      if tablero[y][x] != jugador:
        # pues realmente no ha ganado
        gana = False
        # continua con el siguiente
        continue
    # si realmente ganó
    if gana == True:
      return gana
  # regresa gana
  return gana

In [7]:
# verifica si ya ganó
# si tiene 3 en línea diagonalmente
def gana_diagonal(tablero, jugador):
  # asume que ya ganó
  gana = True
  # inicia en la primer celda vertical
  y = 0
  # recorre horizontalmente
  for x in range(len(tablero)):
    # si no hay 3 en línea
    # usa el mismo valor de x en y
    # para checar la diagonal, ej: (2,2)
    if tablero[x, x] != jugador:
      # pues realmente no ha ganado
      gana = False
  # si realmente ganó
  if gana:
    return gana
  gana = True
  # si aún no gana
  if gana:
    for x in range(len(tablero)):
      y = len(tablero) - 1 - x
      if tablero[x, y] != jugador:
        gana = False
  # regresa gana
  return gana

In [8]:
# verifica si hay empate
def evalua(tablero):
  # asume que
  ganador = 0
  # verifica ambos jugadores
  for jugador in [1, 2]:
    # verifica todas las opciones de ganar
    if (gana_horizontal(tablero, jugador) or
      gana_vertical(tablero, jugador) or
      gana_diagonal(tablero, jugador)):
      # el ganador es el jugador actual
      ganador = jugador
  # prueba si son verdaderos
  if np.all(tablero != 0) and ganador == 0:
    ganador = -1
  # regresa ganador
  return ganador


In [9]:
# inicia el juego
def inicia_juego():
  # crea tablero y asigna jugadores (0,1)
  print("Tablero incial")
  tablero, ganador, contador = crea_tablero(), 0, 1
  # muestra tablero
  print(tablero,"\n")
  # pausa por 2 segundos
  sleep(2)
  # verifica ganador
  while ganador == 0:
    # verifica ambos jugadores
    for jugador in [1, 2]:
      # realiza una jugada
      tablero = movimiento_aleatorio(tablero, jugador)
      print("Tablero después del movimiento: " + str(contador))
      print(tablero,"\n")
      sleep(2)
      contador += 1
      ganador = evalua(tablero)
      if ganador != 0:
        break
  return ganador

In [11]:
# prueba el código
print("El ganador es: " + str(inicia_juego()))


Tablero incial
[[0 0 0]
 [0 0 0]
 [0 0 0]] 

Tablero después del movimiento: 1
[[0 0 0]
 [0 0 1]
 [0 0 0]] 

Tablero después del movimiento: 2
[[0 0 0]
 [0 2 1]
 [0 0 0]] 

Tablero después del movimiento: 3
[[0 0 0]
 [0 2 1]
 [1 0 0]] 

Tablero después del movimiento: 4
[[0 0 2]
 [0 2 1]
 [1 0 0]] 

Tablero después del movimiento: 5
[[1 0 2]
 [0 2 1]
 [1 0 0]] 

Tablero después del movimiento: 6
[[1 0 2]
 [2 2 1]
 [1 0 0]] 

Tablero después del movimiento: 7
[[1 0 2]
 [2 2 1]
 [1 1 0]] 

Tablero después del movimiento: 8
[[1 2 2]
 [2 2 1]
 [1 1 0]] 

Tablero después del movimiento: 9
[[1 2 2]
 [2 2 1]
 [1 1 1]] 

El ganador es: 1
